apiVersion: v1
kind: Service
metadata:
  name: liteoss
spec:
  selector:
    name: liteoss
  ports:
    - name: service-http
      port: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liteoss
spec:
  replicas: 1
  selector:
    matchLabels:
      name: liteoss
  template:
    metadata:
      name: liteoss
    spec:
      containers:
        - name: liteoss
          image: zwischenspiell/liteoss:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: service-http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: schema
              mountPath: /schema
      volumes:
        - name: liteoss-schema
          hostPath:
            path: /mnt/foo-bar/liteoss-schema