name: build

on: workflow_dispatch

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: musl-setup
        run: |
          mkdir /opt/musl
          mkdir /opt/zlib
          wget --no-verbose https://zlib.net/zlib-1.3.1.tar.gz -O zlib.tar.gz
          wget --no-verbose https://more.musl.cc/10/x86_64-linux-musl/x86_64-linux-musl-native.tgz -O musl.tar.gz
          tar xf musl.tar.gz -C /opt/musl
          tar xf zlib.tar.gz -C /opt/zlib
          echo "TOOLCHAIN_DIR=/opt/musl/x86_64-linux-musl-native" >> $GITHUB_ENV

      - name: musl-path
        run: |
          echo "CC=$TOOLCHAIN_DIR/bin/gcc" >> $GITHUB_ENV
          echo "$TOOLCHAIN_DIR/bin" >> $GITHUB_PATH

      - name: musl-zlib
        working-directory: /opt/zlib/zlib-1.3.1
        run: |
          ./configure --prefix=$TOOLCHAIN_DIR --static
          make
          make install

      - name: gradle
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew nativeCompile -P'enableStatic=true'

      - name: upload-bin
        uses: actions/upload-artifact@v4
        with:
          name: liteoss
          path: build/native/nativeCompile/liteoss
          compression-level: 9

      - name: upload-jar
        uses: actions/upload-artifact@v4
        with:
          name: liteoss.jar
          path: build/libs/lite-oss-all.jar
          compression-level: 9

      - name: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker-release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zwischenspiell/liteoss:1.0.0-RC
